/**
 * Cards made in the Card Forge. Generated by tools/import_forge.mjs; don't edit by hand.
 * Merged on top of CARD_CATALOG in shared/cards.js (same id = the Forge version wins).
 */

export const FORGE_CARDS = {};
