// Brings cards from the Card Forge into the game.
//
//   node tools/import_forge.mjs <alleyway-cards.zip | unzipped folder>
//
// Takes the Forge's "Export all" download (card_catalog.json + cards/<id>.png) and:
//   1. writes shared/cards_forge.js (card rules data, merged into CARD_CATALOG),
//   2. copies the card images to assets/cards and godot/assets/cards,
//   3. regenerates godot/data/cards.json.
// The Forge library is the source of truth: cards removed there are removed here too.
// Then commit, push, and on the server run:  node backend/scripts/sync_cards.mjs
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, copyFileSync, statSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = process.argv[2];
if (!src || !existsSync(src)) {
    console.error('usage: node tools/import_forge.mjs <alleyway-cards.zip | folder>');
    process.exit(2);
}

// ── 1. Unpack ────────────────────────────────────────────────────────────────
let dir = src;
if (statSync(src).isFile()) {
    dir = mkdtempSync(join(tmpdir(), 'forge-'));
    if (process.platform === 'win32') {
        const q = (p) => `'${p.replace(/'/g, "''")}'`;
        execFileSync('powershell', ['-NoProfile', '-Command',
            `Expand-Archive -LiteralPath ${q(src)} -DestinationPath ${q(dir)} -Force`]);
    } else {
        execFileSync('unzip', ['-q', src, '-d', dir]);          // Linux / macOS
    }
}
const catalogPath = findFile(dir, 'card_catalog.json');
if (!catalogPath) fail(`No card_catalog.json in ${src}. Use the Forge's "Export all" download.`);
const exported = JSON.parse(readFileSync(catalogPath, 'utf8'));
const artDir = join(dirname(catalogPath), 'cards');

// ── 2. Clean up each card ────────────────────────────────────────────────────
const TYPES = ['gang_member', 'leader', 'hustle', 'ambush'];
const cards = {};
const warnings = [];
for (const [key, raw] of Object.entries(exported)) {
    const id = String(raw.id || key).trim();
    if (!/^[a-z0-9_]+$/.test(id)) {
        warnings.push(`"${raw.name}": game ID "${id}" should be lower-case letters, digits and _ only; skipped.`);
        continue;
    }
    if (!TYPES.includes(raw.cardType)) warnings.push(`${id}: unknown card type "${raw.cardType}".`);
    const unit = raw.cardType === 'gang_member' || raw.cardType === 'leader';
    const c = {
        id,
        name: String(raw.name || id),
        clan: String(raw.clan || raw.clanTag || 'nebula'),
        cardType: raw.cardType,
        authority: int(raw.authority),
        tributeCost: int(raw.tributeCost),
        rarity: Math.min(5, Math.max(1, int(raw.rarity) || 1)),
        clanTag: String(raw.clanTag || raw.clan || ''),
        effectKey: raw.effectKey || '',
        art_url: id,
        code: raw.code || '',
        flavourText: raw.flavourText || '',
        effectText: raw.effectText || '',
        effects: Array.isArray(raw.effects) ? raw.effects.map(cleanEffect) : [],
    };
    if (unit) {
        c.attack = int(raw.attack);
        c.defense = int(raw.defense);
        c.level = int(raw.level) || 1;
        c.subtype = raw.subtype || 'brawler';
        c.promotesTo = raw.promotesTo || null;
    }
    if (raw.cardType === 'leader' && raw.awakenCondition) c.awakenCondition = raw.awakenCondition;
    cards[id] = c;
}
for (const c of Object.values(cards)) {
    if (c.promotesTo && !cards[c.promotesTo]) warnings.push(`${c.id}: promotes to "${c.promotesTo}", which isn't in the export.`);
    if (!existsSync(join(artDir, `${c.id}.png`))) warnings.push(`${c.id}: no card image in the export.`);
}
const names = {};
for (const c of Object.values(cards)) (names[c.name] ||= []).push(c.id);
for (const [n, ids] of Object.entries(names)) {
    if (ids.length > 1) warnings.push(`Name "${n}" is used by ${ids.join(', ')}; the server needs unique names (e.g. add "Lv.2").`);
}

// ── 3. Write the data, copy the art, regenerate Godot's data ────────────────
const before = await currentForgeCards();
writeFileSync(join(ROOT, 'shared/cards_forge.js'),
    `/**\n * Cards made in the Card Forge. Generated by tools/import_forge.mjs; don't edit by hand.\n` +
    ` * Merged on top of CARD_CATALOG in shared/cards.js (same id = the Forge version wins).\n */\n\n` +
    `export const FORGE_CARDS = ${JSON.stringify(cards, null, 4)};\n`);

let copied = 0;
for (const target of ['assets/cards', 'godot/assets/cards']) {
    const to = join(ROOT, target);
    if (!existsSync(to)) mkdirSync(to, { recursive: true });
    for (const c of Object.values(cards)) {
        const from = join(artDir, `${c.id}.png`);
        if (existsSync(from)) {
            copyFileSync(from, join(to, `${c.id}.png`));
            if (target === 'assets/cards') copied++;
        }
    }
}
execFileSync(process.execPath, [join(ROOT, 'godot/tools/export_cards.mjs')], { stdio: 'inherit' });

const added = Object.keys(cards).filter(id => !before[id]);
const removed = Object.keys(before).filter(id => !cards[id]);
console.log(`\nImported ${Object.keys(cards).length} Forge cards (${added.length} new, ${removed.length} removed), ${copied} images.`);
if (added.length) console.log(`  new: ${added.join(', ')}`);
if (removed.length) console.log(`  removed: ${removed.join(', ')} (their image files are left in place)`);
for (const w of warnings) console.log(`  ! ${w}`);
console.log(`\nNext: commit and push, then on the server:\n  git pull && node backend/scripts/sync_cards.mjs && sudo systemctl restart alleyway-backend`);

// ── helpers ──────────────────────────────────────────────────────────────────
function int(v) { return Math.trunc(Number(v ?? 0)) || 0; }

function cleanEffect(e) {
    const out = {};
    for (const k of ['when', 'do', 'target', 'until', 'clan', 'kind', 'if']) if (e[k] != null && e[k] !== '') out[k] = String(e[k]);
    for (const k of ['atk', 'def', 'amount', 'n']) if (e[k] != null && e[k] !== '') out[k] = int(e[k]);
    if (e.once) out.once = true;
    return out;
}

function findFile(base, name) {
    for (const entry of readdirSync(base, { withFileTypes: true })) {
        const p = join(base, entry.name);
        if (entry.isFile() && entry.name === name) return p;
        if (entry.isDirectory()) {
            const found = findFile(p, name);
            if (found) return found;
        }
    }
    return null;
}

async function currentForgeCards() {
    try {
        const mod = await import(pathToFileURL(join(ROOT, 'shared/cards_forge.js')).href + `?t=${Date.now()}`);
        return mod.FORGE_CARDS || {};
    } catch {
        return {};
    }
}

function fail(msg) {
    console.error(msg);
    process.exit(1);
}
